### ISSUE TITLE
Table Information Duplication

### ISSUE THREAD

**Issue by FrederickGeek8** [Derek-Wds/UH-backend#4]
In the log table and medicine table, we have columns for doctors' names and patients' names. We shouldn't do this! If the doctor or patient changes their name, then the table becomes out of date.

**Comment by Derek-Wds** [comment]
Well, you are right but I guess we shouldn't consider that? Otherwise how can we link the log with patient and doctor? Simply use their phones? I mean this will reduce the information the log, detailed log and diagnosis have.

**Comment by FrederickGeek8** [comment]
It's just a simple inner join on the phone numbers of the doctors and patients... Surely it's doable. You can output the same information still.

Also we have to consider it since editing your profile is one of the features we've had the longest...

**Comment by Derek-Wds** [comment]
I know, but again I don't know how to do a join table or foreign key stuff on sqlalchemy... There is always a bug in it...

**Comment by FrederickGeek8** [comment]
If you really can't figure it out, just manually do it in Python. AKA, filter doctor by doctor phone then output the doctor name

**Comment by Derek-Wds** [comment]
Fix it in the latest push. Closed.
